[2021-05-09 05:29:58,238] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: helloworld_dag.t4 2021-05-07T00:00:00+00:00 [queued]>
[2021-05-09 05:29:58,256] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: helloworld_dag.t4 2021-05-07T00:00:00+00:00 [queued]>
[2021-05-09 05:29:58,258] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-09 05:29:58,259] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-09 05:29:58,261] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-09 05:29:58,287] {taskinstance.py:1089} INFO - Executing <Task(MyOperator): t4> on 2021-05-07T00:00:00+00:00
[2021-05-09 05:29:58,306] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'helloworld_dag', 't4', '2021-05-07T00:00:00+00:00', '--job-id', '119', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/helloworld.py', '--cfg-path', '/tmp/tmp9o8e49i9', '--error-file', '/tmp/tmpoo81l3oa']
[2021-05-09 05:29:58,308] {standard_task_runner.py:77} INFO - Job 119: Subtask t4
[2021-05-09 05:29:58,300] {standard_task_runner.py:52} INFO - Started process 59 to run task
[2021-05-09 05:29:58,381] {logging_mixin.py:104} INFO - Running <TaskInstance: helloworld_dag.t4 2021-05-07T00:00:00+00:00 [running]> on host 2900f64db589
[2021-05-09 05:29:58,462] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=helloworld_dag
AIRFLOW_CTX_TASK_ID=t4
AIRFLOW_CTX_EXECUTION_DATE=2021-05-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-07T00:00:00+00:00
[2021-05-09 05:29:58,463] {logging_mixin.py:104} INFO - Hello abc
[2021-05-09 05:29:58,513] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=helloworld_dag, task_id=t4, execution_date=20210507T000000, start_date=20210509T052958, end_date=20210509T052958
[2021-05-09 05:29:58,559] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-09 05:29:58,609] {local_task_job.py:146} INFO - Task exited with return code 0
